#!/usr/bin/env ruby

require "chino"
require "active_support/all"

include Chino

command = ARGV.shift

if !File.exists? "Chinofile"
	puts "This directory has no Chinofile. Please create one before running chino"
	exit(1)
end

config = Config.new() do 
	proc = Proc.new {}
	eval File.read("Chinofile"), proc.binding, "Chinofile"
end

if command == "build"

elsif command == "gen"
	class_type = ARGV.shift
	if File.exists?("#{config.data_path}/templates/#{class_type}.j.erb")
		cls_name = ARGV.shift.camelize
		renderer = ERB.new(File.read("#{config.data_path}/templates/#{class_type}.j.erb"))
		File.write("#{cls_name}.j", renderer.result(binding))
	else
		puts "Class type #{class_type} not supported"
		exit(1)
	end

else
	Website.setup(config)
	Website.run!
end
